### ISSUE TITLE
Keeps getting something exploded

### ISSUE THREAD

**Issue by nomstradamus** [pokanop/kubedev#1]
[GIN] 2020/06/22 - 05:04:16 | 500 |  3.308247799s |       127.0.0.1 | GET      /api/default/exec?command=get+pods&json=true

2020/06/22 05:04:18 [Recovery] 2020/06/22 - 05:04:18 panic recovered:
GET /api/default/exec?command=get+namespaces&json=true HTTP/1.1
Host: localhost:9898
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://localhost:9898/default/configmaps
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0

exit status 1
/Users/relferreira/GitHub/kubedev/main.go:87 (0x1c9d2ec)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/recovery.go:48 (0x15130d3)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:84 (0x151248e)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:361 (0x150a6a6)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:326 (0x1509ee3)
/usr/local/go/src/net/http/server.go:2802 (0x12dddd3)
/usr/local/go/src/net/http/server.go:1890 (0x12d9674)
/usr/local/go/src/runtime/asm_amd64.s:1357 (0x105c700)

[GIN] 2020/06/22 - 05:04:18 | 500 |  3.013505635s |       127.0.0.1 | GET      /api/default/exec?command=get+namespaces&json=true
[cors] 2020/06/22 05:04:18 HandlerFunc: Actual request
[cors] 2020/06/22 05:04:18   Actual request no headers added: missing origin
[]string{"get", "secrets", "-n", "default", "-o", "json"}

2020/06/22 05:04:18 [Recovery] 2020/06/22 - 05:04:18 panic recovered:
GET /api/default/exec?command=get+secrets&json=true HTTP/1.1
Host: localhost:9898
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Referer: http://localhost:9898/default/secrets
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0

exit status 1
/Users/relferreira/GitHub/kubedev/main.go:87 (0x1c9d2ec)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/recovery.go:48 (0x15130d3)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/logger.go:84 (0x151248e)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:108 (0x1501c53)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:361 (0x150a6a6)
/Users/relferreira/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:326 (0x1509ee3)
/usr/local/go/src/net/http/server.go:2802 (0x12dddd3)
/usr/local/go/src/net/http/server.go:1890 (0x12d9674)
/usr/local/go/src/runtime/asm_amd64.s:1357 (0x105c700)

**Comment by saheljalal** [comment]
I think you have the wrong project 😄 

You're looking for this likely: https://github.com/relferreira/kubedev
